[project]
name = 'kyc-token-access-control'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.kyc-token-access-control]
path = 'contracts/kyc-token-access-control.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
